STA:
  enable: true
  frames: 3
SFPUs:
  use: "PU-Net"
  upsampling_ratio: 4
  PU-Net:
    learning_rate: 0.001
  PU-GCN:
  MPU:
  PU-GAN:
data:
  dyna: "data/dyna_poisson_8192_resampled.h5"
  pu1k: "data/pu1k.h5"
  enable_patch: false
  num_of_patches: 16
  size_of_dense_patch: 512
  batch_size: 16
  prefetch: 5
